openapi: 3.0.3
info:
  title: Udonggeum Authentication API
  version: 1.0.0
  description: API contract for user authentication (login, register, logout, token refresh)

servers:
  - url: http://localhost:8080/api
    description: Local development server
  - url: https://api.udonggeum.com/api
    description: Production server (HTTPS required)

paths:
  /auth/register:
    post:
      summary: Register a new user
      operationId: register
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  minLength: 6
                  example: "password123"
                name:
                  type: string
                  minLength: 1
                  example: "홍길동"
                phone:
                  type: string
                  pattern: "^01[0-9]-?[0-9]{3,4}-?[0-9]{4}$"
                  example: "010-1234-5678"
      responses:
        '201':
          description: User created successfully, returns auth tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "이미 사용 중인 이메일입니다"
                status: 409

  /auth/login:
    post:
      summary: Authenticate user and return tokens
      operationId: login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
      responses:
        '200':
          description: Login successful, returns auth tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "이메일 또는 비밀번호가 올바르지 않습니다"
                status: 401
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      summary: Logout user (optional backend cleanup)
      operationId: logout
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Logout successful (no content)
        '401':
          description: Unauthorized (token invalid or missing)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/refresh:
    post:
      summary: Refresh access token using refresh token
      operationId: refreshToken
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '401':
          description: Refresh token invalid or expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "세션이 만료되었습니다. 다시 로그인해주세요"
                status: 401

  /auth/me:
    get:
      summary: Get current authenticated user
      operationId: getMe
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized (token invalid or missing)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - email
        - name
        - role
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          format: email
          example: "user@example.com"
        name:
          type: string
          example: "홍길동"
        phone:
          type: string
          nullable: true
          example: "010-1234-5678"
        role:
          type: string
          enum: [user, admin]
          example: "user"
        created_at:
          type: string
          format: date-time
          example: "2025-11-03T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-11-03T10:00:00Z"

    Tokens:
      type: object
      required:
        - access_token
        - refresh_token
      properties:
        access_token:
          type: string
          description: "JWT access token (expires in 15-30 minutes)"
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        refresh_token:
          type: string
          description: "JWT refresh token (expires in 7 days)"
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    AuthResponse:
      type: object
      required:
        - message
        - user
        - tokens
      properties:
        message:
          type: string
          example: "로그인 성공"
        user:
          $ref: '#/components/schemas/User'
        tokens:
          $ref: '#/components/schemas/Tokens'

    Error:
      type: object
      required:
        - message
        - status
      properties:
        message:
          type: string
          description: "Korean error message for user display"
          example: "이메일 또는 비밀번호가 올바르지 않습니다"
        status:
          type: integer
          example: 401
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT access token in Authorization header: Bearer <token>"
